export const SHAPES = [
    {
        id: 1,
        name: 'Bola',
        codename: 'sphere',
        stimulation_title: 'Tahukah Kamu?',
        problem_identification_title: 'Tahukah Kamu?',
        description: 'Bola adalah objek geometri dalam ruang tiga dimensi yang merupakan permukaan dari bola, analog dengan objek melingkar dalam dua dimensi, yaitu "lingkaran" adalah batas dari "cakram".',
        v_formula: '(4/3)*PI*r^3',
        lp_formula: '4*PI*r^2',
        n_vertices: 0,
        n_edges: 0,
        n_faces: 1,
    },
    {
        id: 2,
        name: 'Tabung',
        codename: 'cylinder',
        stimulation_title: 'Tahukah Kamu?',
        problem_identification_title: 'Tahukah Kamu?',
        description: 'Tabung atau silinder adalah bangun ruang tiga dimensi yang dibentuk oleh dua buah lingkaran identik yang sejajar dan sebuah persegi panjang yang mengelilingi kedua lingkaran tersebut. Tabung memiliki 3 sisi dan 2 rusuk.',
        v_formula: 'PI*r^2*t',
        lp_formula: '2*PI*r*(r+t)',
        n_vertices: 0,
        n_edges: 2,
        n_faces: 3,
    },
    {
        id: 3,
        name: 'Prisma',
        codename: 'prism',
        stimulation_title: 'Tahukah Kamu?',
        problem_identification_title: 'Tahukah Kamu?',
        description: 'Dalam geometri, prisma adalah bangun ruang tiga dimensi yang dibatasi oleh alas dan tutup identik berbentuk segi-n dan sisi-sisi tegak berbentuk persegi atau persegi panjang. Dengan kata lain prisma adalah bangun ruang yang mempunyai penampang melintang yang selalu sama dalam bentuk dan ukuran. Prisma segi-n memiliki n + 2 sisi, 3n rusuk dan 2n titik sudut.',
        v_formula: 'LA*t',
        lp_formula: '(2*LA)+(KA*t)',
        n_vertices: -1,
        n_edges: -1,
        n_faces: -1,
    },
    {
        id: 4,
        name: 'Kerucut',
        codename: 'cone',
        stimulation_title: 'Tahukah Kamu?',
        problem_identification_title: 'Tahukah Kamu?',
        description: 'Dalam geometri, kerucut adalah sebuah limas istimewa yang beralas lingkaran. Kerucut memiliki 2 sisi, 1 rusuk, dan 1 titik sudut.',
        v_formula: '(1/3)*PI*r^2*t',
        lp_formula: 'PI*r*(r+s)',
        n_vertices: 1,
        n_edges: 1,
        n_faces: 2,
    },
    {
        id: 5,
        name: 'Limas',
        codename: 'pyramid',
        stimulation_title: 'Tahukah Kamu?',
        problem_identification_title: 'Tahukah Kamu?',
        description: 'Dalam geometri, limas adalah bangun ruang tiga dimensi yang dibatasi oleh alas berbentuk segi-n dan sisi-sisi tegak berbentuk segitiga. Limas memiliki n + 1 sisi, 2n rusuk dan n + 1 titik sudut.',
        v_formula: '(1/3)*LA*t',
        lp_formula: 'LA+LST',
        n_vertices: -1,
        n_edges: -1,
        n_faces: -1,
    },
];

// export const SHAPE_NAMES = ['Bola', 'Tabung', 'Prisma', 'Kerucut', 'Limas'];